### ISSUE TITLE
Main page has a title of "&middot; HelSec"

### ISSUE THREAD

**Issue by supertassu** [HelSec/helsec.github.io#2]
It either should have something before the middot or not have the middot at all. I assume no-one disagrees with removing it entirely?

**Comment by hasanen** [comment]
Yeah, I don't have any problems for that. The issue is probably in here https://github.com/HelSec/helsec.github.io/blob/master/_includes/head.html#L12 and in settings.

**Comment by supertassu** [comment]
fixed
